# Generated by Django 4.0 on 2022-04-15 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comic',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('marvel_id', models.PositiveIntegerField(default=1, unique=True, verbose_name='marvel ids')),
                ('title', models.CharField(default='', max_length=120, verbose_name='titles')),
                ('description', models.TextField(default='', verbose_name='descriptions')),
                ('price', models.FloatField(default=0.0, max_length=5, verbose_name='prices')),
                ('stock_qty', models.PositiveIntegerField(default=0, verbose_name='stock qty')),
                ('picture', models.URLField(default='', verbose_name='pictures')),
            ],
            options={
                'verbose_name': 'Comic',
                'verbose_name_plural': 'Comics',
            },
        ),
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('favorite', models.BooleanField(default=False, verbose_name='Favorite')),
                ('cart', models.BooleanField(default=False, verbose_name='carts')),
                ('wished_qty', models.PositiveIntegerField(default=0, verbose_name='wished qty')),
                ('buied_qty', models.PositiveIntegerField(default=0, verbose_name='buied qty')),
                ('comic_id', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='e_commerce.comic', verbose_name='Comic')),
                ('user_id', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='auth.user', verbose_name='User')),
            ],
            options={
                'verbose_name': 'Wishlist',
                'verbose_name_plural': 'Wishlists',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100, verbose_name='Pais')),
                ('state', models.CharField(max_length=100, verbose_name='Provincia/Estado')),
                ('city', models.CharField(default='', max_length=100, verbose_name='Ciudad')),
                ('postal_code', models.CharField(max_length=15, verbose_name='Codigo Postal')),
                ('cell_phone_number', models.CharField(max_length=20, verbose_name='Numero de Tel')),
                ('user', models.OneToOneField(blank=True, default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='auth.user', verbose_name='User')),
            ],
            options={
                'verbose_name': 'profile',
            },
        ),
    ]
